id = "mojolicious"
name = "Mojolicious"
version = "0.1.0"
schema_version = 1
authors = ["Jan Limpens"]
description = "Mojolicious template (html.ep) support for Zed"
repository = "https://github.com/janlimpens/zed-mojolicious"

[grammars.html_ep]
repository = "https://github.com/janlimpens/tree-sitter-html-ep"
commit = "f43d247230137caeea9075454873dd041538bfc8"
